source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FYActionSheet_Example', :exclusive => true do
  pod "FYActionSheet", :path => "../"
end

target 'FYActionSheet_Tests', :exclusive => true do
  pod "FYActionSheet", :path => "../"

  
end
